version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: neuropsy-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    container_name: neuropsy-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: neuropsy-frontend
    build:
      context: ./frontend/neuropsy-app-frontend
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - backend

volumes:
  postgres_data: